package Views;

import Controllers.QuizController;
import Models.ModelQuiz;
import javax.swing.*;

public class AddView extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private QuizController quizController;
    
    /**
     * Creates new form AddView
     */
    public AddView(MainFrame mainFrame, QuizController quizController) {
        this.mainFrame = mainFrame;
        this.quizController = quizController;
        initComponents();
        setupListeners();
    }
    
    private void setupListeners() {
        for (java.awt.event.ActionListener al : jButtonAdd.getActionListeners()) {
            jButtonAdd.removeActionListener(al);
        }
        jButtonAdd.addActionListener(evt -> {
            String question = jTextAreaQuestion.getText();
            String option1 = jTextFieldOption1.getText();
            String option2 = jTextFieldOption2.getText();
            String option3 = jTextFieldOption3.getText();
            String option4 = jTextFieldOption4.getText();
            String answer = jTextFieldCorrect.getText();

            if (question.isEmpty() || option1.isEmpty() || option2.isEmpty() || option3.isEmpty() || option4.isEmpty() || answer.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ModelQuiz quiz = new ModelQuiz(question, option1, option2, option3, option4, answer);
            quizController.insertQuiz(quiz);
            JOptionPane.showMessageDialog(this, "Quiz added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        });

        for (java.awt.event.ActionListener al : jButtonClear.getActionListeners()) {
            jButtonClear.removeActionListener(al);
        }
        jButtonClear.addActionListener(evt -> clearFields());
    }
    
    private void clearFields() {
        jTextAreaQuestion.setText("");
        jTextFieldOption1.setText("");
        jTextFieldOption2.setText("");
        jTextFieldOption3.setText("");
        jTextFieldOption4.setText("");
        jTextFieldCorrect.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelQuestion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuestion = new javax.swing.JTextArea();
        jTextFieldOption1 = new javax.swing.JTextField();
        jTextFieldOption2 = new javax.swing.JTextField();
        jTextFieldOption3 = new javax.swing.JTextField();
        jTextFieldOption4 = new javax.swing.JTextField();
        jTextFieldCorrect = new javax.swing.JTextField();
        jLabelOption1 = new javax.swing.JLabel();
        jLabelOption2 = new javax.swing.JLabel();
        jLabelOption3 = new javax.swing.JLabel();
        jLabelOption4 = new javax.swing.JLabel();
        jLabelCorrect = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jButtonBack.setBackground(new java.awt.Color(0, 51, 51));
        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(197, 224, 224));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 51));
        jLabelTitle.setText("ADD QUESTION");

        jLabelQuestion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelQuestion.setForeground(new java.awt.Color(0, 51, 51));
        jLabelQuestion.setText("Question");

        jTextAreaQuestion.setBackground(new java.awt.Color(219, 249, 249));
        jTextAreaQuestion.setColumns(20);
        jTextAreaQuestion.setForeground(new java.awt.Color(0, 51, 51));
        jTextAreaQuestion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaQuestion);

        jTextFieldOption1.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldOption1.setForeground(new java.awt.Color(0, 51, 51));

        jTextFieldOption2.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldOption2.setForeground(new java.awt.Color(0, 51, 51));

        jTextFieldOption3.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldOption3.setForeground(new java.awt.Color(0, 51, 51));

        jTextFieldOption4.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldOption4.setForeground(new java.awt.Color(0, 51, 51));

        jTextFieldCorrect.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldCorrect.setForeground(new java.awt.Color(0, 51, 51));

        jLabelOption1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOption1.setForeground(new java.awt.Color(0, 51, 51));
        jLabelOption1.setText("Option 1");

        jLabelOption2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOption2.setForeground(new java.awt.Color(0, 51, 51));
        jLabelOption2.setText("Option 2");

        jLabelOption3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOption3.setForeground(new java.awt.Color(0, 51, 51));
        jLabelOption3.setText("Option 3");

        jLabelOption4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOption4.setForeground(new java.awt.Color(0, 51, 51));
        jLabelOption4.setText("Option 4");

        jLabelCorrect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCorrect.setForeground(new java.awt.Color(0, 51, 51));
        jLabelCorrect.setText("Correct Answer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuestion)
                            .addComponent(jLabelOption1)
                            .addComponent(jLabelOption2)
                            .addComponent(jLabelOption3)
                            .addComponent(jLabelOption4)
                            .addComponent(jLabelCorrect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOption3)
                            .addComponent(jTextFieldOption4)
                            .addComponent(jTextFieldCorrect)
                            .addComponent(jTextFieldOption1)
                            .addComponent(jTextFieldOption2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQuestion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOption1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOption2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOption3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOption3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOption4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOption4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCorrect))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonClear.setBackground(new java.awt.Color(0, 51, 51));
        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("Clear");

        jButtonAdd.setBackground(new java.awt.Color(0, 51, 51));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClear))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        mainFrame.showView(MainFrame.MAIN);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JLabel jLabelCorrect;
    private javax.swing.JLabel jLabelOption1;
    private javax.swing.JLabel jLabelOption2;
    private javax.swing.JLabel jLabelOption3;
    private javax.swing.JLabel jLabelOption4;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaQuestion;
    private javax.swing.JTextField jTextFieldCorrect;
    private javax.swing.JTextField jTextFieldOption1;
    private javax.swing.JTextField jTextFieldOption2;
    private javax.swing.JTextField jTextFieldOption3;
    private javax.swing.JTextField jTextFieldOption4;
    // End of variables declaration//GEN-END:variables
}
