package Views;

import Controllers.QuizController;
import Models.ModelQuiz;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class DeleteView extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private QuizController quizController;
    private int selectedQuizId;
    /**
     * Creates new form Update
     */
    public DeleteView(MainFrame mainFrame, QuizController quizController) {
        this.mainFrame = mainFrame;
        this.quizController = quizController;
        this.selectedQuizId = -1;
        initComponents();
        setupListeners();
        loadQuizzes();
    }
    
    private void loadQuizzes() {
        List<ModelQuiz> quizzes = quizController.getAllQuiz();
        DefaultTableModel model = (DefaultTableModel) jTableData.getModel();
        model.setRowCount(0);
        for (ModelQuiz quiz : quizzes) {
            model.addRow(new Object[]{
                quiz.getQuestion(),
                quiz.getOptionA(),
                quiz.getOptionB(),
                quiz.getOptionC(),
                quiz.getOptionD(),
                quiz.getAnswer()
            });
        }
    }
    
    private void setupListeners() {
        jTableData.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = jTableData.getSelectedRow();
                if (selectedRow >= 0) {
                    List<ModelQuiz> quizzes = quizController.getAllQuiz();
                    selectedQuizId = quizzes.get(selectedRow).getIdQuiz();
                    jTextAreaQuestion.setText(quizzes.get(selectedRow).getQuestion());
                    jTextFieldOption1.setText(quizzes.get(selectedRow).getOptionA());
                    jTextFieldOption2.setText(quizzes.get(selectedRow).getOptionB());
                    jTextFieldOption3.setText(quizzes.get(selectedRow).getOptionC());
                    jTextFieldOption4.setText(quizzes.get(selectedRow).getOptionD());
                    jTextFieldCorrect.setText(quizzes.get(selectedRow).getAnswer());
                }
            }
        });

        for (java.awt.event.ActionListener al : jButtonDelete.getActionListeners()) {
            jButtonDelete.removeActionListener(al);
        }
        jButtonDelete.addActionListener(evt -> {
            if (selectedQuizId == -1) {
                JOptionPane.showMessageDialog(this, "Please select a quiz to delete!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this quiz?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                quizController.deleteQuiz(selectedQuizId);
                JOptionPane.showMessageDialog(this, "Quiz deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadQuizzes();
                clearFields();
            }
        });
    }
    
    private void clearFields() {
        jTextAreaQuestion.setText("");
        jTextFieldOption1.setText("");
        jTextFieldOption2.setText("");
        jTextFieldOption3.setText("");
        jTextFieldOption4.setText("");
        jTextFieldCorrect.setText("");
        selectedQuizId = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableData = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelQuestion = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaQuestion = new javax.swing.JTextArea();
        jTextFieldOption1 = new javax.swing.JTextField();
        jTextFieldOption2 = new javax.swing.JTextField();
        jTextFieldOption3 = new javax.swing.JTextField();
        jTextFieldOption4 = new javax.swing.JTextField();
        jTextFieldCorrect = new javax.swing.JTextField();
        jLabelOption1 = new javax.swing.JLabel();
        jLabelOption2 = new javax.swing.JLabel();
        jLabelOption3 = new javax.swing.JLabel();
        jLabelOption4 = new javax.swing.JLabel();
        jLabelCorrect = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jButtonBack.setBackground(new java.awt.Color(0, 51, 51));
        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(197, 224, 224));

        jScrollPane2.setForeground(new java.awt.Color(0, 51, 51));

        jTableData.setBackground(new java.awt.Color(219, 249, 249));
        jTableData.setForeground(new java.awt.Color(0, 51, 51));
        jTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Question", "Option 1", "Option 2", "Option 3", "Option 4", "Correct Answer"
            }
        ));
        jScrollPane2.setViewportView(jTableData);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 51));
        jLabelTitle.setText("UPDATE QUESTION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(197, 224, 224));

        jLabelQuestion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelQuestion.setForeground(new java.awt.Color(0, 51, 51));
        jLabelQuestion.setText("Question");

        jTextAreaQuestion.setBackground(new java.awt.Color(219, 249, 249));
        jTextAreaQuestion.setColumns(20);
        jTextAreaQuestion.setForeground(new java.awt.Color(0, 51, 51));
        jTextAreaQuestion.setRows(5);
        jScrollPane3.setViewportView(jTextAreaQuestion);

        jTextFieldOption1.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldOption1.setForeground(new java.awt.Color(0, 51, 51));

        jTextFieldOption2.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldOption2.setForeground(new java.awt.Color(0, 51, 51));

        jTextFieldOption3.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldOption3.setForeground(new java.awt.Color(0, 51, 51));

        jTextFieldOption4.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldOption4.setForeground(new java.awt.Color(0, 51, 51));

        jTextFieldCorrect.setBackground(new java.awt.Color(219, 249, 249));
        jTextFieldCorrect.setForeground(new java.awt.Color(0, 51, 51));

        jLabelOption1.setBackground(new java.awt.Color(204, 255, 255));
        jLabelOption1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOption1.setForeground(new java.awt.Color(0, 51, 51));
        jLabelOption1.setText("Option 1");

        jLabelOption2.setBackground(new java.awt.Color(204, 255, 255));
        jLabelOption2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOption2.setForeground(new java.awt.Color(0, 51, 51));
        jLabelOption2.setText("Option 2");

        jLabelOption3.setBackground(new java.awt.Color(204, 255, 255));
        jLabelOption3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOption3.setForeground(new java.awt.Color(0, 51, 51));
        jLabelOption3.setText("Option 3");

        jLabelOption4.setBackground(new java.awt.Color(204, 255, 255));
        jLabelOption4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelOption4.setForeground(new java.awt.Color(0, 51, 51));
        jLabelOption4.setText("Option 4");

        jLabelCorrect.setBackground(new java.awt.Color(204, 255, 255));
        jLabelCorrect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCorrect.setForeground(new java.awt.Color(0, 51, 51));
        jLabelCorrect.setText("Correct Answer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQuestion)
                    .addComponent(jLabelOption1)
                    .addComponent(jLabelOption2)
                    .addComponent(jLabelOption3)
                    .addComponent(jLabelOption4)
                    .addComponent(jLabelCorrect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldOption1)
                    .addComponent(jScrollPane3)
                    .addComponent(jTextFieldOption2)
                    .addComponent(jTextFieldOption3)
                    .addComponent(jTextFieldOption4)
                    .addComponent(jTextFieldCorrect))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuestion))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOption1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOption2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOption3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOption3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOption4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOption4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCorrect))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonDelete.setBackground(new java.awt.Color(0, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        mainFrame.showView(MainFrame.MAIN);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabelCorrect;
    private javax.swing.JLabel jLabelOption1;
    private javax.swing.JLabel jLabelOption2;
    private javax.swing.JLabel jLabelOption3;
    private javax.swing.JLabel jLabelOption4;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableData;
    private javax.swing.JTextArea jTextAreaQuestion;
    private javax.swing.JTextField jTextFieldCorrect;
    private javax.swing.JTextField jTextFieldOption1;
    private javax.swing.JTextField jTextFieldOption2;
    private javax.swing.JTextField jTextFieldOption3;
    private javax.swing.JTextField jTextFieldOption4;
    // End of variables declaration//GEN-END:variables
}
