package Views;

import Controllers.QuizController;
import Models.ModelQuiz;
import java.util.List;
import javax.swing.*;

public class PlayOfflineView extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private QuizController quizController;
    private List<ModelQuiz> quizzes;
    private int currentQuizIndex;
    private int score;
    
    /**
     * Creates new form PlayView
     */
    public PlayOfflineView(MainFrame mainFrame, QuizController quizController) {
        this.mainFrame = mainFrame;
        this.quizController = quizController;
        this.currentQuizIndex = 0;
        this.score = 0;
        initComponents();
        setupListeners();
        loadQuizzes();
        displayQuiz();
    }
    
    private void loadQuizzes(){
        quizzes = quizController.getRandomQuiz();
        if(quizzes.isEmpty()){
            JOptionPane.showMessageDialog(this, "No quizzes available", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void displayQuiz(){
        if(currentQuizIndex < quizzes.size()){
            ModelQuiz quiz = quizzes.get(currentQuizIndex);
            jLabelQuestion.setText(quiz.getQuestion());
            jButtonOption1.setText(quiz.getOptionA());
            jButtonOption2.setText(quiz.getOptionB());
            jButtonOption3.setText(quiz.getOptionC());
            jButtonOption4.setText(quiz.getOptionD());
        } else {
            // Kuis selesai, tampilkan skor
            mainFrame.showView(MainFrame.SCORE);
            ((ScoreView) mainFrame.getContentPane().getComponent(4)).setScore(score); // Update skor di ScoreView
        }
    }
    
    private void checkAnswer(String selectedOption) {
        ModelQuiz quiz = quizzes.get(currentQuizIndex);
        if (selectedOption.equals(quiz.getAnswer())) {
            score += 10; // Tambah 10 poin untuk jawaban benar
            JOptionPane.showMessageDialog(this, "Correct!", "Result", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Wrong! Correct answer: " + quiz.getAnswer(), "Result", JOptionPane.ERROR_MESSAGE);
        }
        currentQuizIndex++;
        displayQuiz();
    }
    
    private void setupListeners() {
        // Remove existing listeners if necessary and add new ones
        for (java.awt.event.ActionListener al : jButtonOption1.getActionListeners()) {
            jButtonOption1.removeActionListener(al);
        }
        jButtonOption1.addActionListener(evt -> checkAnswer(jButtonOption1.getText()));

        for (java.awt.event.ActionListener al : jButtonOption2.getActionListeners()) {
            jButtonOption2.removeActionListener(al);
        }
        jButtonOption2.addActionListener(evt -> checkAnswer(jButtonOption2.getText()));

        for (java.awt.event.ActionListener al : jButtonOption3.getActionListeners()) {
            jButtonOption3.removeActionListener(al);
        }
        jButtonOption3.addActionListener(evt -> checkAnswer(jButtonOption3.getText()));

        for (java.awt.event.ActionListener al : jButtonOption4.getActionListeners()) {
            jButtonOption4.removeActionListener(al);
        }
        jButtonOption4.addActionListener(evt -> checkAnswer(jButtonOption4.getText()));

        for (java.awt.event.ActionListener al : jButtonNext.getActionListeners()) {
            jButtonNext.removeActionListener(al);
        }
        jButtonNext.addActionListener(evt -> {
            currentQuizIndex++;
            displayQuiz();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jPanelQuestion = new javax.swing.JPanel();
        jLabelQuestion = new javax.swing.JLabel();
        jButtonOption1 = new javax.swing.JButton();
        jButtonOption2 = new javax.swing.JButton();
        jButtonOption3 = new javax.swing.JButton();
        jButtonOption4 = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jButtonBack.setBackground(new java.awt.Color(0, 51, 51));
        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanelQuestion.setBackground(new java.awt.Color(197, 224, 224));
        jPanelQuestion.setForeground(new java.awt.Color(255, 255, 255));

        jLabelQuestion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelQuestion.setForeground(new java.awt.Color(0, 51, 51));
        jLabelQuestion.setText("Soalnyh Nnti Disni");

        javax.swing.GroupLayout jPanelQuestionLayout = new javax.swing.GroupLayout(jPanelQuestion);
        jPanelQuestion.setLayout(jPanelQuestionLayout);
        jPanelQuestionLayout.setHorizontalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuestion)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanelQuestionLayout.setVerticalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuestion)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jButtonOption1.setBackground(new java.awt.Color(196, 224, 224));
        jButtonOption1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonOption1.setForeground(new java.awt.Color(0, 51, 51));
        jButtonOption1.setText("Option 1");

        jButtonOption2.setBackground(new java.awt.Color(197, 224, 224));
        jButtonOption2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonOption2.setForeground(new java.awt.Color(0, 51, 51));
        jButtonOption2.setText("Option 2");

        jButtonOption3.setBackground(new java.awt.Color(197, 224, 224));
        jButtonOption3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonOption3.setForeground(new java.awt.Color(0, 51, 51));
        jButtonOption3.setText("Option 3");

        jButtonOption4.setBackground(new java.awt.Color(197, 224, 224));
        jButtonOption4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonOption4.setForeground(new java.awt.Color(0, 51, 51));
        jButtonOption4.setText("Option 4");

        jButtonNext.setBackground(new java.awt.Color(0, 51, 51));
        jButtonNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNext.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNext.setText("Next");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelQuestion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOption1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOption2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOption3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOption4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack)
                    .addComponent(jPanelQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOption1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOption2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOption3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOption4)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNext)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        mainFrame.showView(MainFrame.MAIN);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonOption1;
    private javax.swing.JButton jButtonOption2;
    private javax.swing.JButton jButtonOption3;
    private javax.swing.JButton jButtonOption4;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JPanel jPanelQuestion;
    // End of variables declaration//GEN-END:variables
}
