package Views;

public class PlayMethodView extends javax.swing.JPanel {
    private MainFrame mainFrame;
    /**
     * Creates new form NewJPanel
     */
    public PlayMethodView(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        setupListeners();
    }
    
    private void setupListeners() {
        // Remove existing listeners to avoid duplicates and add new ones
        for (java.awt.event.ActionListener al : jButtonOnline.getActionListeners()) {
            jButtonOnline.removeActionListener(al);
        }
        jButtonOnline.addActionListener(evt -> mainFrame.showView(MainFrame.PLAY_ONLINE));

        for (java.awt.event.ActionListener al : jButtonOffline.getActionListeners()) {
            jButtonOffline.removeActionListener(al);
        }
        jButtonOffline.addActionListener(evt -> mainFrame.showView(MainFrame.PLAY_OFFLINE));

        for (java.awt.event.ActionListener al : jButtonBack.getActionListeners()) {
            jButtonBack.removeActionListener(al);
        }
        jButtonBack.addActionListener(evt -> mainFrame.showView(MainFrame.MAIN));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jButtonOnline = new javax.swing.JButton();
        jButtonOffline = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 300));

        jButtonBack.setBackground(new java.awt.Color(0, 51, 51));
        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 51));
        jLabelTitle.setText("Choos How You Want to Play");

        jButtonOnline.setBackground(new java.awt.Color(0, 51, 51));
        jButtonOnline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonOnline.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOnline.setText("Online");
        jButtonOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOnlineActionPerformed(evt);
            }
        });

        jButtonOffline.setBackground(new java.awt.Color(0, 51, 51));
        jButtonOffline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonOffline.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOffline.setText("Offline");
        jButtonOffline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOfflineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabelTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOffline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(24, 24, 24)
                .addComponent(jButtonOnline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOffline)
                .addGap(18, 18, 18)
                .addComponent(jButtonBack)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOnlineActionPerformed
        mainFrame.showView(MainFrame.PLAY_ONLINE);
    }//GEN-LAST:event_jButtonOnlineActionPerformed

    private void jButtonOfflineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOfflineActionPerformed
        mainFrame.showView(MainFrame.PLAY_OFFLINE);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonOfflineActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        mainFrame.showView(MainFrame.MAIN);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonOffline;
    private javax.swing.JButton jButtonOnline;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
