package Views;

import Controllers.QuizController;

public class ScoreView extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private QuizController quizController;
    /**
     * Creates new form ScoreView
     */
    public ScoreView(MainFrame mainFrame, QuizController quizController) {
        this.mainFrame = mainFrame;
        this.quizController = quizController;
        initComponents();
        setupListeners();
    }
    
    public void setScore(int score) {
        jLabelScore.setText(String.valueOf(score));
    }

    private void setupListeners() {
        for (java.awt.event.ActionListener al : jButtonReplay.getActionListeners()) {
            jButtonReplay.removeActionListener(al);
        }
        jButtonReplay.addActionListener(evt -> mainFrame.showView(MainFrame.PLAY_METHOD));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jButtonReplay = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 51));
        jLabelTitle.setText("YOUR SCORE");

        jLabelScore.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelScore.setForeground(new java.awt.Color(0, 51, 51));
        jLabelScore.setText("100");

        jButtonReplay.setBackground(new java.awt.Color(0, 51, 51));
        jButtonReplay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonReplay.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReplay.setText("Replay");

        jButtonBack.setBackground(new java.awt.Color(0, 51, 51));
        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabelTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabelScore))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBack)
                            .addComponent(jButtonReplay))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelScore)
                .addGap(43, 43, 43)
                .addComponent(jButtonReplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBack)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        mainFrame.showView(MainFrame.MAIN);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonReplay;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
